---
# tasks file for roles/zabbix

- name: Add Zabbix repository
  yum:
    name: https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/zabbix-release-4.4-1.el7.noarch.rpm
    state: present

- name: Install Zabbix
  package:
    name: zabbix-agent
    state: present
  notify: start zabbix-agent

- name: Copy zabbix config
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent
