---
# tasks file for roles/zabbix

- name: Add Zabbix repository
  yum:
    name: https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/zabbix-release-4.4-1.el7.noarch.rpm
    state: present

- name: Install Zabbix
  package:
    name: "{{ install_zabbix }}"
    state: present
  notify:
    - start zabbix-server
    - start zabbix-agent
    - database
    - selinux

- name: Copy zabbix config
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
  notify: restart zabbix-agent

- name: Copy nginx-zabbix config
  template:
    src: nginx_zabbix.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Install SELinux utils
  yum: 
    name: policycoreutils-python
    state: present
