---
# tasks file for roles/webserver

- name: Install epel
  yum:
    name: epel-release
    state: present

- name: Install borgbackup
  yum:
    name: borgbackup
    state: present
  notify: borgbackup
