---
# tasks file for roles/webserver

- name: Add PHP-FPM repository
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Format name for php version specific repos name.
  set_fact:
    php_repos_with_version: "remi-php73"

- name: Enable php repo
  ini_file:
    dest: "/etc/yum.repos.d/{{ php_repos_with_version }}.repo"
    section: "{{ php_repos_with_version }}"
    option: enabled
    value: "1"

- name: Install PHP-FPM packages
  package:
    name: "{{ php_modules }}"
    state: present
  notify: start php-fpm

- name: Create NGINX config file
  copy:
    src: www.conf
    dest: /etc/php-fpm.d/www.conf
  notify: restart php-fpm
